### ISSUE TITLE
error

### ISSUE THREAD

**Issue by piotrekkrol7** [nikooo777/ckSurf#1]
L 08/21/2016 - 14:35:31: [SM] Blaming: ckSurf.smx()
L 08/21/2016 - 14:35:31: [SM] Call stack trace:
L 08/21/2016 - 14:35:31: [SM]   [0] PrintToChat
L 08/21/2016 - 14:35:31: [SM]   [1] Line 1849, csgo/addons/sourcemod/scripting/ckSurf/commands.sp::Client_Hide()
L 08/21/2016 - 14:38:48: Error log file session closed.
i have this

**Comment by nikooo777** [comment]
Hi, i don't see anything wrong, do you have the latest sm version?
also careful with my latest commit, there is a bug in the rank colors


-----
involved code:

```
public Action Client_Hide(int client, int args)
{
	HideMethod(client);
	if (!g_bHide[client])
		PrintToChat(client, "%t", "Hide1", MOSSGREEN, WHITE);
	else
		PrintToChat(client, "%t", "Hide2", MOSSGREEN, WHITE);
	return Plugin_Handled;
}
```
