### ISSUE TITLE
Zone deleting issue

### ISSUE THREAD

**Issue by Destinyg133** [nikooo777/ckSurf#13]
There is a problem with a single zone deleteing
you cant just delete one zone that you have made, it says its succesefully deleted but it just stays there

only way is deleteing ALL map zones at once.

**Comment by blackhawk74** [comment]
A workaround for this is to delete the zone, then press Reload Zones. The zone will now then be properly deleted.

**Comment by Destinyg133** [comment]
thank you

**Comment by nikooo777** [comment]
Hello,
thanks I will take a look as soon as i have a bit of time :)

sounds like an easy fix for a silly bug

**Comment by nikooo777** [comment]
i think i found a fix for this, it'll be included in the next commit

**Comment by Destinyg133** [comment]
thank you :D

**Comment by nikooo777** [comment]
solved in previous commit :) (untested)
