### ISSUE TITLE
[suggestion] Database and TeleToPreviousStageZone

### ISSUE THREAD

**Issue by Destinyg133** [nikooo777/ckSurf#15]
Could you make for cksurf to calculate  (recalculate points) all ppl from database and not just first 1ooo? 

also making TeleToPreviousStageZone would be awesome, it would be same as TeleToStart, but it wont put you all the way back to start, it will put you on the last zone you touched (good for staged maps of there are major skips)

**Comment by fluffyst** [comment]
If you use a checker zone without a validator, it already does this.

**Comment by Destinyg133** [comment]
but it doesnt teleport you back instantly, or im wrong?

**Comment by fluffyst** [comment]
It does

**Comment by Destinyg133** [comment]
sorry, forgot to close this one, ty for help
