### ISSUE TITLE
Capitalized chat triggers do not work

### ISSUE THREAD

**Issue by blackhawk74** [nikooo777/ckSurf#16]
For example, if a user types !B instead of !b, the !B shows up in chat and the user does not get teleported to the bonus. !R instead of !r also has the same result. This is an issue with cksurf chat processing enabled or disabled.

**Comment by nikooo777** [comment]
Hey,
I will patch this in the next update

**Comment by nikooo777** [comment]
I just doublechecked but i couldn't reproduce your issue.

On my servers typing !b or !B and !r or !R produce the same effect.

**Comment by Destinyg133** [comment]
for me !R works, but !B doesnt and !SPEC or !SPECTATE doesnt work

**Comment by 2called-chaos** [comment]
This fixes it, I don't understand why it's there in the first place?!? Bypassing checkspam?

https://github.com/2called-chaos/ckSurf/commit/79b15ae368e8912527111831ec69566837d8983a
