### ISSUE TITLE
error while start

### ISSUE THREAD

**Issue by luca152** [nikooo777/ckSurf#18]
L 12/13/2016 - 17:11:24: [SM] Exception reported: [ckSurf] Unable to connect to database (Configuration "cksurf" not found)
L 12/13/2016 - 17:11:24: [SM] Blaming: ckSurf.smx
L 12/13/2016 - 17:11:24: [SM] Call stack trace:
L 12/13/2016 - 17:11:24: [SM]   [0] SetFailState
L 12/13/2016 - 17:11:24: [SM]   [1] Line 158, ckSurf/sql.sp::db_setupDatabase
L 12/13/2016 - 17:11:24: [SM]   [2] Line 1849, D:\ckSurf\csgo\addons\sourcemod\scripting\ckSurf.sp::OnPluginStart
L 12/13/2016 - 17:11:24: [SM] Unable to load plugin "ckSurf.smx": Error detected in plugin startup (see error logs)

please help

**Comment by nikooo777** [comment]
Hi, please check the logs and make sure you follow the instructions.

You didn't configure a database in database.cfg

**Comment by luca152** [comment]
i configured my database, where do i find the log?

**Comment by nikooo777** [comment]
please check the documentation or the sourcemod thread, this question is asked multiple times every week
