### ISSUE TITLE
Replay bots not being loaded

### ISSUE THREAD

**Issue by Venki23** [nikooo777/ckSurf#19]
Hello, I've been using plugin for a long time, and I've noticed that replay bots simply don't spawn from time to time. It seems to be happening more often now. The runs seem to be saved just fine in server files, but ingame, only "BOT (one of default names)" spawns and does nothing, just runs around. Any fix for this? Thanks.
SourceMod 1.8.0.5957, ckSurf 1.18

Edit: Had the same problem on 1.19, only switched back to 1.18 some time ago, guess the problem is the same for both versions

**Comment by nikooo777** [comment]
hey, 

Do you have any error logs to help me with? without logs there is so much I can do... I know the bot isn't always good at saving records, but if there is a record saved it should always replay them. It does for me at least.

BTW, stay away from sm1.9, it doesn't work

**Comment by 2called-chaos** [comment]
I have the same problem and it happens every single time so if you need something to debug, ping me ;-) There is no error message (server log, nor sm log/error log) but here is a log with `developer 1` from when I change a map to when I'm in the game and looking at the bot running somewhere.

https://gist.github.com/2called-chaos/7116e3acb4d238bdc97084275d072ae2

I figured that disabling/enabling the replay bot fixes it, but when I retry (reconnect) the bot is screwed again. I assume that it breaks when there is no one on the server?

I thought it might be related to my mp_restartgame in the main.cfg but it doesn't make a difference if I remove it.

**Comment by 2called-chaos** [comment]
I figured why it won't load replays for me until I stop/start the bot and I don't know why exactly it DOES work when I toggle the setting because the reason is this:

    "[FunCS] GOTV<32><BOT><Unassigned>" changed name to "Chaos wer sonst? (01:07:73)"

So disabling GOTV fixes the problem but I wonder if we can fix this because I kinda want GOTV :D

@Venki23 Do you have GOTV enabled as well?
