### ISSUE TITLE
cksurf error tro several sm-versions

### ISSUE THREAD

**Issue by Destinyg133** [nikooo777/ckSurf#29]
L 03/05/2017 - 017:14: [ckSurf.smx] [ckSurf] SQL Error (sql_selectPlayerNameCallback): Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '='

also players who has clan tags are shown like this
http://imgur.com/a/pZPPY

**Comment by zAfLu** [comment]
What is your Database collation?

**Comment by Destinyg133** [comment]
hello zackboom's friend :D

i have managed to fix issue by changing from latin1_swedish_ci to utf8_general_ci

now i still have problem with my surf bots not being on server for some reason
do you know how to fix that?

**Comment by 2called-chaos** [comment]
Have you tried compiling from git master yourself? There was an issue #19 fixed but I don't know if niko made a build yet.

**Comment by Destinyg133** [comment]
yea i have, problem is its not on server aswell. no bots at all

**Comment by 2called-chaos** [comment]
@Destinyg133 Niko said that recording doesn't work all the time. Can you verify that a recording for the map is present in `addons/sourcemod/data/cKreplays` and/or try enabling infobot if you haven't? Also check what your `bot_quota` and `bot_quota_mode` values are (ck should set them as needed but maybe it gives insight).

**Comment by Destinyg133** [comment]
all records for 147 maps are in folder Ckreplays
info bot is on
bot_quota 0
bot_quota_mode "normal"

**Comment by zAfLu** [comment]
replay_bot.nav is still in maps folder?

**Comment by Destinyg133** [comment]
.rec are there, .nav are not, hmm, any solution?

**Comment by zAfLu** [comment]
Copy the replay_bot.nav froh the archive to your maps folder

**Comment by Destinyg133** [comment]
oops, my bad, was checking wrong folder, yea bot_replay.nav is there

also when i connect with hlsw to server, bots arent there like it used to be

**Comment by Destinyg133** [comment]
any other help?

**Comment by Destinyg133** [comment]
for some reason, there was this launch option -nohltv, that was breaking bots from spawning, 

FIXED, gonna close issue
