### ISSUE TITLE
[suggestion] Map vote

### ISSUE THREAD

**Issue by Destinyg133** [nikooo777/ckSurf#30]
is there anyone willing to edit map vote to add this
On last 2 min of current map vote starts (as is)
vote comes, example
surf_1
surf_2
surf_3
surf_4
surf_5
Extend current map(add this)

**Comment by blackhawk74** [comment]
Use a different map chooser, this has nothing to do with cksurf. There are several available.

**Comment by Destinyg133** [comment]
ah okay then, ty
