### ISSUE TITLE
Replay Bot issues

### ISSUE THREAD

**Issue by ZipYourLip** [nikooo777/ckSurf#34]
Edit: issue as been resolved.

**Comment by 2called-chaos** [comment]
Have you changed the tickrate of the server by chance? That would break existing playback recordings and behave like you have described.

You can try to temporarily rename the directory `cKreplays` or a specific demo in it and complete the map (it should record even if you don't break record), is it still broken?
The full path to the replays is `addons/sourcemod/data/cKreplays`.

**Comment by ZipYourLip** [comment]
The server tickrate has remained the same.
I'll see if the renaming works.

**Comment by ZipYourLip** [comment]
Yeah renaming didn't seem to do the trick..

**Comment by ZipYourLip** [comment]
bump

**Comment by Vantriii** [comment]
I have the same issue only on certain maps (e.g. surf utopia)

**Comment by Destinyg133** [comment]
Same on utopia, using golden knife
Bassically when you have higher speed than you should your bot goes crazy, but only on some maps
