### ISSUE TITLE
Problems on newer versions of MySQL

### ISSUE THREAD

**Issue by RixPox** [nikooo777/ckSurf#43]
So my host just decided to upgrade MySQL to a higher version than 5.7.5 and now ran into some problems with ck which causes issues with fetching records from mysql:

1. Jun 6 19:02:49: L 06/06/2017 - 17:02:49: [ckSurf.smx] [ckSurf] SQL Error (SQL_selectBonusCountCallback): Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column '58e29ef6cde5f51c941319b3.ck_zones.zoneid' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

2. Jun 6 19:02:49: L 06/06/2017 - 17:02:49: [ckSurf.smx] [ckSurf] SQL Error (sql_selectMapRecordCallback): In aggregated query without GROUP BY, expression #2 of SELECT list contains nonaggregated column '58e29ef6cde5f51c941319b3.ck_playertimes.name'; this is incompatible with sql_mode=only_full_group_by

3. Jun 6 19:02:49: L 06/06/2017 - 17:02:49: [ckSurf.smx] [ckSurf] SQL Error (SQL_selectFastestBonusCallback): Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column '58e29ef6cde5f51c941319b3.ck_bonus.name' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

4. Jun 6 19:02:49: L 06/06/2017 - 17:02:49: [ckSurf.smx] [ckSurf] SQL Error (sql_selectRecordCheckpointsCallback): Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column '58e29ef6cde5f51c941319b3.b.cp1' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

I've read about the only_full_group_by issue on stackoverflow but cant make heads or tails of what I should change in sql.sp to make those erroring parts compactible with the newer version of MySQL, and my host cannot downgrade due to other clients needing a newer version of MySQL, so I'll just leave this here for someone else to figure out. 👍

**Comment by TandelK** [comment]
I think you need to add sql_mode="" in your Mysql Configuration file

**Comment by TandelK** [comment]
This will remove strict mode  from  mysql

**Comment by TandelK** [comment]
**I didnt see that you are using any type of hosting company . I am afraid for it . Better to use own Hosted SQL Server for this purpose specially as this plugin is almost like 2 years old now and has old MYSQL Scripts. I recommend talking to your host and make them add speciifc permission for your user that can use sql_mode=""**

**Comment by 2called-chaos** [comment]
MySQL's sql_mode setting can be changed at runtime for a given session/connection only.

Therefore you could try to add this after [line #166 here](https://github.com/nikooo777/ckSurf/blob/master/csgo/addons/sourcemod/scripting/ckSurf/sql.sp#L166) but still in the if statement and compile it.

```sp
SQL_FastQuery(g_hDb, "SET sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));");
```
