### ISSUE TITLE
New update broke Bot as GOTV new update is out

### ISSUE THREAD

**Issue by TandelK** [nikooo777/ckSurf#44]
Today CSGO Update broke ckSurf Bot as GOTV has been updated with additional relay's with 2 GOTV now. So it broke the recording of Bot .

**Comment by mloveless1227** [comment]
I concur with this statement. All my surf servers have non-working replay bots. Using the latest 1.8 SM and verified all .nav files, replays, and database information is accurate and functional.

**Comment by valantislevas** [comment]
I also have issues with bot.. is working last week and after update now the bot stays on spawn doing nothing.. any way to fix that?

**Comment by rogeraabbccdd** [comment]
Update your soucemod

**Comment by TandelK** [comment]
@rogeraabbccdd Already started working. Closing it
