### ISSUE TITLE
Incorrect number of total ranks displayed on chat/hud

### ISSUE THREAD

**Issue by pabp** [nikooo777/ckSurf#5]
Just as it says, each time someone sets a PB or a new server record both the HUD and the chat information incorrectly increment the total number of ranks on that map. I checked the actual stats with !maptop and everything's correct there, so it's something just to do with the information displayed to the HUD rather than a database problem.

**Comment by nikooo777** [comment]
Hi,
thanks for reporting this issue.
I will be handling all the issues reported in the past weeks very soon.

**Comment by blackhawk74** [comment]
Can also confirm this issue, see an example here: http://puu.sh/rJzPM/5afcacb476.jpg

**Comment by nikooo777** [comment]
so, i just checked this bug and apparently it's meant to be right. 

The count you see there is relative to ALL maps played, so if you have more servers or more maps, that count refers to all players having more than 0 points in the table ck_playerrank

**Comment by Destinyg133** [comment]
well it wasnt like that in original version, so it would be nice if you could somehow make that it like original, i find that feature awful, since some people dont check maptop, and if for example i beat map 5 times, and others do it same but for their record, rank for map could be huge, thats just my opinion :D

**Comment by Destinyg133** [comment]
On bonuses, everything is fine, so its only on normal maps

**Comment by MainFighter** [comment]
Anyone figured out how to actually fix this yet?
Its happening with my server as well, same as this guy.

**Comment by MainFighter** [comment]
This seems to be a issues with only your fork, 1.18 doesn't have the problem.

**Comment by Destinyg133** [comment]
yeo, altho he said thats how it suppose to be, but it would be good if niko.could fix it or return it somehow to previous state, bonus is fine but doing normal maps triggers +1 in numbers of ranks

**Comment by nikooo777** [comment]
if anyone would be so kind to point me to the code region for both bonuses and normal runs i'll try to "revert" the change (I actually don't remember ever touching such a thing)

**Comment by Destinyg133** [comment]
i can confirm its working now fine
