### ISSUE TITLE
ranks title

### ISSUE THREAD

**Issue by Theedgeclan2** [nikooo777/ckSurf#55]
fresh server install the ranks and titles dont work
<a href="https://i.imgur.com/y6qERmE.jpg" target="_blank"><img src="https://i.imgur.com/y6qERmE.jpg" alt="rh1pkvr" style="max-width:100%;"></a>
<a href="https://i.imgur.com/so8MTRR.jpg" target="_blank"><img src="https://i.imgur.com/so8MTRR.jpg" alt="rh1pkvr" style="max-width:100%;"></a>

limegreen TO lime worked
even with the stocked ranks they show this too

**Comment by M-archand** [comment]
This has been an issue for 1 year now, see issue #12 for more information
