### ISSUE TITLE
Server Crash on startup

### ISSUE THREAD

**Issue by Sandman007** [nikooo777/ckSurf#56]
Hello. I am currently using Influx Timer with no issues but I want to switch back to ckSurf. I however can't get it to run without it crashing the server. I am using MySQL but it also crashes using sqlite.

I tried a fresh install of the latest SourceMod (1.8.0.6027) and latest MM.

The plugin seems to load fine. I can sometimes get on the server quick enough to see the timer before the server crashes.

This is the only thing in the logs I could find that seemed important or related to ckSurf. 

`
Server logging disabled.
userid "2" not found
`

It also says in console 
`
"Segmentation fault (core dumped)"
`

**Comment by Sandman007** [comment]
Fixed by convert the ckSurf DB and all tables to utf8mb4_general_ci collation. They were all made as italian by the plugin itself. This needs to get fixed.

**Comment by nikooo777** [comment]
is your database/server somehow installed in italian? I never hardcoded something like that in the plugin
