### ISSUE TITLE
New Records don't save. And Convar for disable for the bet points on the challenges dont work.

### ISSUE THREAD

**Issue by DaskleineUef** [nikooo777/ckSurf#6]
So first i got since the last Update from Csgo the Bug if someone create a new record. 
It shows "Missing their best time. [rank #99999/2333] Faild to save your  data correctly! Please contact a Admin."
Thats in my error only spaming the time.
[SM] Blaming: ckSurf.smx
[SM] Call stack trace:
[SM]   [1] Line 451, ckSurf/buttonpress.sp::CL_OnEndTimerPress
[SM]   [2] Line 185, ckSurf/surfzones.sp::StartTouch
[SM]   [3] Line 101, ckSurf/surfzones.sp::StartTouchTrigger

And next, cause many boosted with friend (they challenge with points and surrender) I want to turn it off in the convar. But it always on ingame. (at last i remove the lines in cksurf/commands.sp)

See ya,
Das kleine Uef

**Comment by nfs6661** [comment]
I have this problem.

**Comment by nikooo777** [comment]
fixed the challenge for points cvar on commit 85c2d3508302ffb064f0020103ea85341498550c

**Comment by nikooo777** [comment]
also the reason why you have issues is that you don't have the latest SM1.8 version, download it and it'll be fine.
