### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by piotrekkrol7** [nikooo777/ckSurf#8]
hi i have error logs
L 10/15/2016 - 11:36:01: [SM] Exception reported: Using two team colors in one message is not allowed
L 10/15/2016 - 11:36:01: [SM] Blaming: ckSurf.smx
L 10/15/2016 - 11:36:01: [SM] Call stack trace:
L 10/15/2016 - 11:36:01: [SM]   [0] ThrowError
L 10/15/2016 - 11:36:01: [SM]   [1] Line 425, K:\Users\Niko\Desktop\spedit\sm_1_7\include\colors.inc::CFormat
L 10/15/2016 - 11:36:01: [SM]   [2] Line 219, K:\Users\Niko\Desktop\spedit\sm_1_7\include\colors.inc::CPrintToChatEx
L 10/15/2016 - 11:36:01: [SM]   [3] Line 254, K:\Users\Niko\Desktop\spedit\sm_1_7\include\colors.inc::CPrintToChatAllEx
L 10/15/2016 - 11:36:01: [SM]   [4] Line 301, ckSurf/hooks.sp::Say_Hook
L 10/15/2016 - 11:50:05: Error log file session closed.

**Comment by nikooo777** [comment]
you are using 2 team colors in one message, the error says it all.

check that you don't have both blue and red (teamcolors) in a single rank name

By the way, you're not running the latest version i think, because i compiled from Linux last time.

**Comment by piotrekkrol7** [comment]
i have new version and original config surf . What can i do and wher can i change this ?

**Comment by nikooo777** [comment]
download the latest ckSurf.smx from here and upload it to your plugins folder.

For the colors you can find them in addons/sourcemod/configs/skillgroups.cfg

**Comment by piotrekkrol7** [comment]
L 10/15/2016 - 20:27:13: [SM] Exception reported: Using two team colors in one message is not allowed
L 10/15/2016 - 20:27:13: [SM] Blaming: ckSurf.smx
L 10/15/2016 - 20:27:13: [SM] Call stack trace:
L 10/15/2016 - 20:27:13: [SM]   [0] ThrowError
L 10/15/2016 - 20:27:13: [SM]   [1] Line 425, csgo/addons/sourcemod/scripting/include/colors.inc::CFormat
L 10/15/2016 - 20:27:13: [SM]   [2] Line 219, csgo/addons/sourcemod/scripting/include/colors.inc::CPrintToChatEx
L 10/15/2016 - 20:27:13: [SM]   [3] Line 254, csgo/addons/sourcemod/scripting/include/colors.inc::CPrintToChatAllEx
L 10/15/2016 - 20:27:13: [SM]   [4] Line 301, csgo/addons/sourcemod/scripting/ckSurf/hooks.sp::Say_Hook
L 10/15/2016 - 20:42:34: Error log file session closed.

i have this http://wklej.org/id/2912410/ config

**Comment by Bijleveldje** [comment]
Hi,

Try to delete the colors {blue} and {red} from the config to see if that works.

**Comment by nikooo777** [comment]
actually, remove colors from the "name" tag!
only keep them in the "color" tag

**Comment by nikooo777** [comment]
i must correct myself, having the color in the name tag is fair. do what @Bijleveldje said
