### ISSUE TITLE
Cleaner signature not working for Windows

### ISSUE THREAD

**Issue by M-archand** [nikooo777/ckSurf#80]
https://github.com/nikooo777/ckSurf/blob/149caab4cce186fe852973332b9dc794f3cbd601/csgo/addons/sourcemod/gamedata/cleaner.txt#L21

Does anyone have a Windows signature for Cleaner.ext that works? I tried different ones in the orginal [cleaner thread](https://forums.alliedmods.net/showthread.php?t=195008) and the one on here but I keep getting `Unable to load extension "cleaner.ext": Failed to find signature. Please contact the author.`

**Comment by mloveless1227** [comment]
Why did you close this and not provide an answer? This has been a problem for a while now.

**Comment by M-archand** [comment]
Not really relevant to ckSurf I guess. Was just a simple question but clearly no one has an answer after months so might as well close. Really the responsibility of the extension author not anyone here.
