### ISSUE TITLE
CkSurf starting fail.

### ISSUE THREAD

**Issue by StFrosty** [nikooo777/ckSurf#86]
Hey guys! This is my first post so I want to explain it nice. Ok, first, I install CS:GO server on Ubuntu 14.04.05; and then I install Source Mod and Meta Mod.
I install CkSurf 1.18 and I update it to the most recent version (the last month or something I read)
When I start my CS:GO server on surf_ map, I tip "sm plugins list" on the console, it work but ckSurf no.
First Error - Console indicated that ckSurf is not working: **ckSurf.smx (ckSurf): Error detected in plugin startup (see error logs)**
So I see error logs, and this appear: 
L 05/21/2018 - 13:24:47: SourceMod error session started
L 05/21/2018 - 13:24:47: Info (map "surf_mesa_revo_go") (file "errors_20180521.log")
L 05/21/2018 - 13:24:47: [SM] Exception reported: [SURF] Unable to connect to database (Configuration "cksurf" not found)
L 05/21/2018 - 13:24:47: [SM] Blaming: ckSurf.smx
L 05/21/2018 - 13:24:47: [SM] Call stack trace:
L 05/21/2018 - 13:24:47: [SM]   [0] SetFailState
L 05/21/2018 - 13:24:47: [SM]   [1] Line 157, csgo/addons/sourcemod/scripting/ckSurf/sql.sp::db_setupDatabase
L 05/21/2018 - 13:24:47: [SM]   [2] Line 1894, csgo/addons/sourcemod/scripting/ckSurf.sp::OnPluginStart
L 05/21/2018 - 13:24:47: [SM] Unable to load plugin "ckSurf.smx": Error detected in plugin startup (see error logs)
------------------------------
I configured my database.cfg like explain on: https://forums.alliedmods.net/showthread.php?t=264498
and I do the tables like appear here: https://wiki.alliedmods.net/SQL_Admins_(SourceMod)#Configuration
and here: /home/CSGO/Steam/cs_go/csgo/addons/sourcemod/configs/sql-init-scripts/mysql and the archive create_admin.sql
------------------------------
Any idea?

**Comment by nikooo777** [comment]
your database configuration is wrong. it can't connect to it `[SURF] Unable to connect to database (Configuration "cksurf" not found)`

you should also not use this fork anymore. there is a better version called surftimer out there that forked from this repo :)
